theme: jekyll-theme-cayman
title: WillowHQ, the home of the Willow cooperative.
description: WillowHQ was created by Thom Lamb, as a place to surface project ideas, and connect with developers seeking to gain real world experience working on those projects. 
